apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: persons-finder
  namespace: persons-finder-dev
  annotations:
    # For nginx-ingress. Change/remove if you use a different controller.
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: persons-finder-dev.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: persons-finder
                port:
                  number: 8080
