apiVersion: v1
kind: Service
metadata:
  name: persons-finder
  namespace: persons-finder-dev
  labels:
    app: persons-finder
spec:
  type: ClusterIP
  selector:
    app: persons-finder
  ports:
    - name: http
      port: 8080
      targetPort: http
